// GETTERS
export const IS_BACKDROP_ACTIVE = "shared/IS_BACKDROP_ACTIVE"

// MUTATIONS
export const SET_BACKDROP_MODAL = "shared/SET_BACKDROP_MODAL"

// ACTIONS
export const TOGGLE_BACKDROP_MODAL = "shared/TOGGLE_BACKDROP_MODAL"